####################################################
#
# Welcome to GhanaNLP
#
# Product Link : https://ghananlp.org/
# Version : v1.0.0
#
####################################################

# Site settings
title: "Ghana Natural Language Processing (NLP) - Ghana NLP "
email: "natural.language.processing.gh@gmail.com"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ghananlp.org " # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/logo/logo.png"
description: "Open Source Initiative focused on Natural Language Processing (NLP) of Ghanaian Languages, & its Applications to Local Problems"
keywords: "ai, ml, artificial intelligence, ghana, nlp, ghananlp, natural language processing"
# mailclimp: 'https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=4784863884'
facebook: https://www.facebook.com/GhanaNLP
twitter: https://twitter.com/GhanaNLP
github: https://github.com/GhanaNLP
slack: https://ghananlp.slack.com


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-archives


# Site configuration for the Jekyll 2 Pagination Gem
pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 6
  permalink: '/pages/:num/' # Pages are simple html files 
  title: ':title - page :num'
  limit: 0 
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: '' 
  trail: 
    before: 2
    after: 
  extension: 'html'
  indexpage: 'index'

autopages:
  enabled: true
  categories: 
    layouts: 
      - 'category.html'
    title: 'Category -  :cat'
    permalink: '/category/:cat'
  collections:
    layouts: 
      - 'category.html'
    title: ' :coll' # :coll is replaced by the collection name
    permalink: '/:coll/'
    
  
  tags:
    layouts: 
      - 'tag.html'
    title: 'Tag - :tag' # :tag is replaced by the tag name
    permalink: '/tag/:tag'  
      
tag_page_layout: category
tag_page_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: '/category/:name/'

collections:
  services:
    output: true
    permalink: /service/:path/
  projects:
    output: true
    permalink: /project/:path/
    
feed:
  collections:
    posts:
      path: "/index.xml"