# Site settings
title: GhanaNLP
email: natural.language.processing.gh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open Source Initiative focused on Natural Language Processing (NLP) of Ghanaian Languages, & its Applications to Local Problems
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ghananlp
github_username:  ghananlp

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"